# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-16}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"

  minio:
    image: "${MINIO_IMAGE:-minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1}"
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minioadmin}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minioadmin}"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: "${ALPINE_VERSION:-3.20}"
        POSTGRES_VERSION: "${POSTGRES_VERSION:-16}"
        SUPERCRONIC_SHA1SUM: "${SUPERCRONIC_SHA1SUM:-}"
    environment:
      SCHEDULE: "${SCHEDULE:-@weekly}" # optional
      BACKUP_KEEP_DAYS: "${BACKUP_KEEP_DAYS:-7}" # optional
      S3_REGION: "${S3_REGION:-us-east-1}"
      S3_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID:-minioadmin}"
      S3_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY:-minioadmin}"
      S3_BUCKET: "${S3_BUCKET:-demo-backups}"
      S3_PREFIX: "${S3_PREFIX:-backup}"
      S3_ENDPOINT: "${S3_ENDPOINT:-http://minio:9000}"
      S3_S3V4: "${S3_S3V4:-yes}"
      POSTGRES_HOST: "${POSTGRES_HOST:-postgres}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      PASSPHRASE: "${PASSPHRASE:-}"
    depends_on:
      - postgres
      - minio

volumes:
  minio-data:
