# this file is here to facilitate development/testing
# $ docker compose up -d --build --force-recreate

services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-16}"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  backup:
    build:
      context: .
      args:
        ALPINE_VERSION: "${ALPINE_VERSION:-3.20}"
        POSTGRES_VERSION: "${POSTGRES_VERSION:-16}"
        SUPERCRONIC_SHA1SUM: "${SUPERCRONIC_SHA1SUM}"
    environment:
      SCHEDULE: '@weekly' # optional
      BACKUP_KEEP_DAYS: 7 # optional
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: demo-backups
      S3_PREFIX: backup
      S3_ENDPOINT: http://minio:9000
      S3_S3V4: yes
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres
      - minio

volumes:
  minio-data:
